// Code generated by entc, DO NOT EDIT.

package ent

import (
	"app/entity/basic/ent/sample"
	"app/entity/basic/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sampleFields := schema.Sample{}.Fields()
	_ = sampleFields
	// sampleDescName is the schema descriptor for name field.
	sampleDescName := sampleFields[1].Descriptor()
	// sample.DefaultName holds the default value on creation for the name field.
	sample.DefaultName = sampleDescName.Default.(string)
	// sampleDescID is the schema descriptor for id field.
	sampleDescID := sampleFields[0].Descriptor()
	// sample.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sample.IDValidator = sampleDescID.Validators[0].(func(int) error)
}
