// Code generated by entc, DO NOT EDIT.

package ent

import (
	"app/entity/basic/ent/sample"
	"app/entity/basic/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sampleFields := schema.Sample{}.Fields()
	_ = sampleFields
	// sampleDescAge is the schema descriptor for age field.
	sampleDescAge := sampleFields[0].Descriptor()
	// sample.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	sample.AgeValidator = sampleDescAge.Validators[0].(func(int) error)
	// sampleDescName is the schema descriptor for name field.
	sampleDescName := sampleFields[1].Descriptor()
	// sample.DefaultName holds the default value on creation for the name field.
	sample.DefaultName = sampleDescName.Default.(string)
}
